In [1]:
import pickle
#import pickle5 as pickle # colab
import numpy as np
from lifelines.utils import concordance_index
# import urllib
import urllib.request

In [2]:
with open('Regression_Dataset1', 'rb') as handle:
    data = pickle.load(handle)
    y = pickle.load(handle)
    testdata = pickle.load(handle)
    testy = pickle.load(handle)

#target_url = 'http://aais.hanyang.ac.kr/classes/2022_Datasets/Regression_Dataset1'
#with urllib.request.urlopen(target_url) as handle:
#    data = pickle.load(handle)
#    y = pickle.load(handle)
#    testdata = pickle.load(handle)
#    testy = pickle.load(handle)

In [3]:
data = np.max(data.reshape(60000, -1, 5), axis=(2)) # Max poolnig
data = np.column_stack([data*data]+[2*data[:, :-i]*data[:, i:] for i in range(1, 157)]) # phi mapping
testdata = np.max(testdata.reshape(60000, -1, 5), axis=(2)) # Max pooling
testdata = np.column_stack([testdata*testdata]+[2*testdata[:, :-i]*testdata[:, i:] for i in range(1, 157)]) # phi mapping
data.shape

(60000, 12403)

In [4]:
XXT = np.matmul(data.T, data)
Xy = np.matmul(data.T, y)

sigma_sq = 1
sigma_sq0 = 5
invXXT = np.linalg.inv(XXT + sigma_sq/sigma_sq0*np.eye(len(XXT)))

In [5]:
pred_y = np.matmul(data, np.matmul(invXXT, Xy))
print(y, '\n', pred_y)
print('CI:', concordance_index(y, pred_y))
print('\n')

pred_y = np.matmul(testdata, np.matmul(invXXT, Xy))
print(testy, '\n', pred_y)
print('test CI:', concordance_index(testy, pred_y))

[2 4 1 ... 8 7 6] 
 [2.80392022 2.83231369 0.64666128 ... 5.75977757 7.55952277 6.05205954]
CI: 0.9402119047482952


[5 0 9 ... 3 1 6] 
 [ 6.87638784 -0.36992336  8.72606538 ...  4.02446954  1.03844967
  3.33548937]
test CI: 0.9172335128688842
